### PR TITLE
Hi10p should only trigger on h264

### PR DESCRIPTION
**Pull request by Draic**
changed h265 to h264 as this should be the intended codec.

### CODE REVIEW

**Comment by Draic** [comment]
#367

**Comment by croneter** [comment]
I don't get it. H265 is more demanding on CPU than h264. Please explain to me why you would want the less demanding codec being transcoded?

**Comment by Draic** [comment]
because there is no processor on the market that offers hardware decoding for hi10p in h264 as it is a very uncommon h264 profile (only popular in the anime community). The default profile for h264 is 8bit, which most videos are using. So you always have to use software decoding for hi10p and my CPU on the kodi client is too weak for that. 8bit hardware decoding is available but never for 10bit.

BUT this is different in h265. Here 10bit is the standard and better supported profile. In fact every processor on the market that offers hardware decoding for h265 does offer it for 10bit. So having the hi10p option force transcode on this codec is an disadvantage, as I want to make use of the hardware decoding capabilities. There is never a reason why you would want a specific setting for 10bit h265 transcoding as this is the default for ANY h265 video. And there already is a force transcode for h265 option available anyways.

The kodi wiki also explains that hi10p is a term for h264 and the problems of hardware support: http://kodi.wiki/view/Hi10P

I am using the file with the proposed changes already at home and it works perfectly. 

I am happy to answer any further questions you might have

**Comment by croneter** [comment]
Thanks for the detailed answer! I'll include the PR in the next release

**Pull request merged**
