### PR TITLE
change from emby to plex user image

### PR DESCRIPTION
**Pull request by im85288**

### CODE REVIEW

**Comment by im85288** [comment]
I had made an error with only retrieving the banner art but that's now fixed (and handled by fanarttv) with the latest pull request.

**Comment by croneter** [comment]
Cool, thanks very much!

**Comment by croneter** [comment]
Merged it into develop. Thanks again!

**Comment by croneter** [comment]
* How about that API call to fanarttv. What happens if hundred/thousands use the same key?
* I guess we should give people an option to turn off getting fanart from fanarttv

**Comment by im85288** [comment]
I think it will be fine as that key is already used with different addons without any problems..but something to keep an eye on.

Yes I thought about that after committing, maybe another pop up dialog at first sync that asks if they want the extra artwork retrieved.

**Comment by croneter** [comment]
Unfortunately, a full library sync with fanarttv enabled takes forever now :-(. 

I'm thinking of moving this completely away from the actual library sync to some kind of background service running in separate threads

**Comment by im85288** [comment]
Yes it does take quite a bit longer, I guess with rpi it's really slow. A background option sounds good, or the easy way is to just make it one of those options at initial sync time (eg with a warning it will take a bit longer)..for me it probably adds about 5 mins to the initial sync, which I'm happy to take the hit for as it means not needing to use artwork downloader.

**Comment by croneter** [comment]
I have 400 movies, which ain't that much. Initial sync time went up from like 2' to probably 30' on my powerfull PC. What really sucks is that sooner or later, the PMS **will** upgrade/scan items again, which would trigger fanarttv all over again. This is actually what happened to me today...

Hence to me it seems like a much better idea to move fanarttv download away from anything the user might notice.

By the way, to hopefully keep your work to a minimum - did you fork the develop branch now? ;-)

**Comment by im85288** [comment]
Good point with the re trigger, yes agreed moving it to another process which can maybe kick off after the initial scan is probably the way to go.

I did just switch to the develop branch so all good now :) If there's something you'd like me to test or help with the changes just give me a shout. Cheers

**Comment by croneter** [comment]
Tearing my hair out here with Kodi listitems - maybe you know more?

In the custom "On Deck" and "Recently Added" TV video nodes, the episode information does not work. Looks like Kodi has no idea that the items are actually in its database. Can you help?

Thanks :-)

**Comment by im85288** [comment]
I'll definitely have a look, must admit to not having used those nodes. Hopefully it's something easy, but knowing how these things work it's probably not!

**Comment by im85288** [comment]
It seems to work fine for me (I do have direct paths enabled) with the only real problem being the lack of artwork (missing posters etc) 

http://i.imgur.com/7XNSKIE.jpg

Am I missing something here as the "On Deck" and "Recently added" are already available via the standard Kodi nodes (so maybe something that can be left for a rainy day?)

**Comment by croneter** [comment]
Thanks :-). I mean the episode information screen if you hit "i" in those 2 video nodes. It doesn't work for me, kodi tries looking up an nfo file instead of getting the data from the library. 

Don't know about direct paths

**Comment by im85288** [comment]
Yeah I think you missed my second edit...working correctly with direct paths. Must be something to do with how the non direct path file names are stored in the local database.

**Comment by croneter** [comment]
Was my feeling too. But heck it's 1:1 adapted from emby. Plus it works fine if you are not in these 2 nodes. Seems this bug is related to the way the listitems are put together via json

**Comment by im85288** [comment]
Yeah I know I never used the Emby equivalent of those nodes so couldn't say if it worked their or not..plus I was always using direct paths there :) Probably easiest thing to do for now is to remove the nodes (so that no users report errors on it).

**Comment by angelblue05** [comment]
Kodi listitems are wonky for recently added (they don't show info). I couldn't get it to work with plugin paths.

**Comment by im85288** [comment]
Thanks Angel, that confirms that it should be something left for the rainiest day possible :)

**Comment by croneter** [comment]
Hehehe, thanks angelblue!

**Pull request closed without merging**
