### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by rmellid**
Update french translation

### CODE REVIEW

**Comment by croneter** [comment]
Thanks a LOT for the translation!!

Next time, please simply use Transifex: https://www.transifex.com/croneter/pkc. 

I will upload your changes, so there's nothing more you need to do.

**Comment by rmellid** [comment]
Ok, next time, I will use transifex.

**Comment by croneter** [comment]
Uploaded your translations to Transifex. There are still 3 translations missing, could you please have a look on Transifex?

Also, I'd be glad if you added these 3 translations also the Canadian French 😉

**Comment by rmellid** [comment]
I did the 3 translations missing in French.
But i don't have the rights for the canadian french.

**Comment by croneter** [comment]
Thanks! Just apply for the rights :wink:

**Comment by croneter** [comment]
Closed via PR #1168

Many thanks!!

**Pull request closed without merging**
