### PR TITLE
change resentEpisodes to get from Plex instead KodiDb

### PR DESCRIPTION
**Pull request by dettwild**
This covers part 1 of issue #190 as mentioned in the other PR (#199)
The proposal is to change the logic of getting the recently added episodes and pull the list directly from PMS (same as already done for OnDeck) rather than running queries on the kodi db. This became apparent when looking to fix the proper application of 'limit' for the tag-filtered 'recentEpisodes' method where one would need to query ALL episodes initially to then compare to the tag-filtered list of shows (it is possible that the relevant Episodes from shows with the respective Tag appear at the end of the full list as they were added before other episodes of shows with non-relevant tags).
However, this would make the PKC Option "Also show watched episodes" under appearance tweaks obsolete because PMS does not offer the option to turn that off (it includes watched episodes by default).  This PR does NOT make any modification of the settings though.

It may now also be a good time to point out that PMS has 2 ways to show the respective recent Episodes/Shows information:  in the Home-Screen Dashboard they do not show episodes but rather one single poster per show which contains the number of episodes that were added. In the respective Plex TV Show sections however, in the 'recently Added' view, Plex also lists all episodes like done here. Perhaps this could be added to PKC as a new video node also? I have to admit though that the script.skin.helper.widgets supports something similar already called "Recently added TV Shows".
Happy to discuss.

### CODE REVIEW

**Comment by croneter** [comment]
OK, looks good. Please quickly fix the following:
* If something fails, `xbmcplugin.endOfDirectory(HANDLE, False)` should be used. Not only `xbmcplugin.endOfDirectory(HANDLE)`, which defaults to `xbmcplugin.endOfDirectory(HANDLE, True)`

While you're at it and feel like it, and this is really just a matter of taste :-)
* Instead of using `limitcounter = 0` and `limitcounter += 1`, you could use `for limitcounter, item in enumerate(xml)`
* Mind too much whitespace, see e.g. https://www.python.org/dev/peps/pep-0008/ ;-)

**Comment by dettwild** [comment]
Happy to add your changes and learn more on the way ;-).
As you probably realized by know, I am quite a noob with python but a great fan of consistency.
So let me just confirm that I understood what you had in mind and clarify a few things along the way:
- I noticed that some of your code (e.g. getOnDeck - line 782) uses `cacheToDisc=settings('enableTextureCache') == 'true'` as second argument of `xbmcplugin.endOfDirectory`. Would that also make sense here instead of just using 'False' like you mention above?  Also, in some cases the word "return" is added before `xbmcplugin.endOfDirectory` while mostly it is not - does that make any difference?
- most subs in entrypoint.py don't have a second argument when calling `xbmcplugin.endOfDirectory` - would it make sense to also add "False" or the statement `cacheToDisc=settings('enableTextureCache') == 'true'` there?
- I'll try to have a look at your style proposal - but to "defend" myself - I just copied the logic from a different sub in your code ;-)
- as I am not sure yet if I manage to edit this PR (played around quite a bit since), I may end up creating a new PR - hope that is ok also.

Cheers and thanks for your patience and understanding ;-)

**Comment by croneter** [comment]
* Revisit https://docs.python.org/2/tutorial/controlflow.html#keyword-arguments, while having a look at http://mirrors.kodi.tv/docs/python-docs/16.x-jarvis/xbmcplugin.html. It could actually be `endOfDirectory(handle=HANDLE, succeeded=False)`, but that's omitted because we know :-) that the `succeeded=...` is the second argument
* They default to `succeeded=True`, see above
* Regarding style, a nice editor is a HUGE asset. I use Sublime Text with these plugins:
unbenannt
The SublimeLinter piece will automatically format stuff for you and point out mistakes...
* No worries

**Comment by dettwild** [comment]
This is great information - thank you. I currently use Notepad++ but will have a look at Sublime Text (v3 I presume?) once their website is up again.
By the way, are there any good tools what allow for run-time debugging with variable monitoring, step-by-step operations and breakpoints? For now I have been taking the "old school" route of writing everything into the logfile :-o.

With regards to your other points, I hope you don't mind me checking back once more:
- I think I understand the succeeded argument of `endOfDirectory` now (and also that arguments can either be named or provided in correct sequence), I was just confused what you meant with adding the "False" value for succeeded as line  485 of my PR already contains it and line 517 does not need it as succeeded should be 'True' there. Checking again I suspect you mean line 491 of my PR which I gladly adjust. If you really meant this line, you may want to adjust line 756 of your current `entrypoint.py` file also as I had copied it from there.
- If I apply your proposed  `for limitcounter, item in enumerate(xml)` option, I would need to change the exit condition from:  `if limitcounter == limt` to:  `if limitcounter == limit-1` (since enumeration starts at 0 by default) Alternatively, I could use:  `for itemcounter, item in enumerate(xml, start=1)`.  Which option do you prefer? I kinda like the second one better, but am happy to go with your preference.
- Lastly, would you mind giving me a few examples where I used too much whitespace? I saw the guidelines, but may be suffering from "can't see the forest for the trees" ;-).
Btw, as a funny side node to style guides: If you have not seen it already, you may wanna check out Season 3 of Silicon Valley - it contains a hilarious episode about Tabs vs. spaces ;-)

**Comment by dettwild** [comment]
Replaced by PR #216 now - hence closing this one. Thanks again for all the help and pointers!

**Pull request closed without merging**
