### PR TITLE
Rev omega supported db

### LINKED ISSUE #1988: Latest omega alpha build revved the db version so it is no longer supported by the addon
https://kodi.tv/article/kodi-omega-alpha-3/

Pretty sure this isnt working right/supported correctly. It also doesn't handle the rev nicely because the old db was still there. When I manually cleared them I got the "this addon doesnt support this db" error which was nice

```
mdarcy:/sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/Database $ ls -la
total 5084
drwxrwx--x  3 u0_a97 sdcard_rw    4096 2023-09-10 17:28 .
drwxrwx--x 10 u0_a97 sdcard_rw    4096 2023-09-10 17:25 ..
-rw-rw----  1 u0_a97 sdcard_rw    6148 2023-05-31 21:24 .DS_Store
-rw-rw----  1 u0_a97 sdcard_rw    4096 2023-05-31 21:24 ._.DS_Store
-rw-rw----  1 u0_a97 sdcard_rw 2048000 2023-09-10 17:00 Addons33.db
drwxrwx--x  2 u0_a97 sdcard_rw    4096 2023-05-31 21:24 CDDB
-rw-rw----  1 u0_a97 sdcard_rw   32768 2023-01-16 13:19 Epg16.db
-rw-rw----  1 u0_a97 sdcard_rw  225280 2023-05-31 21:24 MyMusic82.db
-rw-rw----  1 u0_a97 sdcard_rw  376832 2023-09-10 17:28 MyVideos122.db
-rw-rw----  1 u0_a97 sdcard_rw   53248 2023-09-10 17:28 TV43.db
-rw-rw----  1 u0_a97 sdcard_rw 1523712 2023-09-10 17:26 Textures13.db
-rw-rw----  1 u0_a97 sdcard_rw   20480 2022-11-24 12:40 ViewModes6.db
-rw-rw----  1 u0_a97 sdcard_rw  442368 2023-09-10 17:23 plex-copy.db
-rw-rw----  1 u0_a97 sdcard_rw  442368 2023-09-10 17:25 plex.db
```

https://github.com/xbmc/xbmc/pull/23346

### PR DESCRIPTION
**Pull request by xconverge**
fixes #1988

### CODE REVIEW

**Comment by booleangit** [comment]
Thanks! It would be really nice if this could be merged. 👍

**Comment by xconverge** [comment]
> Thanks! It would be really nice if this could be merged. 👍

In the meantime (if you want) you can just make the edit manually in the addons folder, that is what I did to test 🤷

**Comment by booleangit** [comment]
> In the meantime (if you want) you can just make the edit manually in the addons folder, that is what I did to test 🤷 

That's exactly what I did and it's working indeed. So if the author can merge this and make a new release, anyone can benefit from it. 🙂

**Comment by xconverge** [comment]
@croneter the changes here https://github.com/croneter/PlexKodiConnect/pull/1968 look good, but after upgrading kodi it resulted in plexkodiconnect just silently working on the wrong db in the background when it updated in kodi and not erroring. Therefore new items to sync in the video db just never showed up in kodi. I did not get the correct error message at startup until I deleted the older db version manually. I am wondering if you have any ideas on how to fix this, either by checking for a count of databases > 1 or some sort of autocleanup on syncing, or even just a readme update?

**Comment by booleangit** [comment]
As a side note: I've done a clean install of Kodi to begin with, so there wasn't an existing installation. After installing PKC, it run and gave me the expected incompatibility message. I've then altered variables.py and restarted Kodi. After the restart PKC presented an error message saying Kodi couldn't parse sources.xml. After manually deleting that file, it got automatically recreated and the error message disappeared.

**Comment by GG-76** [comment]
> As a side note: I've done a clean install of Kodi to begin with, so there wasn't an existing installation. After installing PKC, it run and gave me the expected incompatibility message. I've then altered variables.py and restarted Kodi. After the restart PKC presented an error message saying Kodi couldn't parse sources.xml. After manually deleting that file, it got automatically recreated and the error message disappeared.

i tried this procedure but it still says unsupported version :(

**Pull request closed without merging**
