### PR TITLE
Update Kodi 18 Leia DB Change

### PR DESCRIPTION
**Pull request by gismo112**
Hi @croneter,

the DB of Kodi 18 Leia was changed last week.
Here the new DB´s.

Thanks for your nice Plugin.
Greets Gimso

### CODE REVIEW

**Comment by dazedcrazy** [comment]
I posted the same thing over on the Plex forums the other day, reason i didn't do a PR for it was https://github.com/croneter/PlexKodiConnect/issues/339 changing the db number doesnt solve everything. It's only a band aid for now

**Comment by gismo112** [comment]
This is the reason, why i PR this to the hotfix-branch not to the master. It helps just now :-)

**Comment by croneter** [comment]
Thanks for the PR. I agree with @dazedcrazy though - it's not a simple matter of plugging in a new DB number. I would expect all Kodi changes to be taken care of. 

Thus closing this PR

**Comment by gismo112** [comment]
OK. No problem. Was meant for those who can not help themselves ;-)

**Pull request closed without merging**
