### PR TITLE
Added translation for Hungarian language

### PR DESCRIPTION
**Pull request by savage93**

### CODE REVIEW

**Comment by croneter** [comment]
Dude, many thanks! Please use Transifex next time
https://www.transifex.com/croneter/pkc

**Comment by savage93** [comment]
Dear Croneter!

Unfortunately I cannot use Transifex, because I've forgotten my password
for the site (or so it appears), and apparently their password recovery
emails never arrive in my mailbox.
I've attached an updated version of the Hungarian translation I've made
earlier.

Thank you for the continous development of your great addon, keep up the
good work!

Best regards,
Zoltán

croneter <notifications@github.com> ezt írta (időpont: 2018. ápr. 6., P,
15:28):

**Comment by croneter** [comment]
@savage93 I don't see the Hungarian file here in this Pull Request. Can you upload it again in this conversation thread?

**Comment by savage93** [comment]
Oops, I've thought that you'd get the file as an email attachment, my bad. I've created a new PR with the updated file, so you should be able to merge the changes now.

**Pull request merged**
