### PR TITLE
Add Korean strings.po

### PR DESCRIPTION
**Pull request by so-o-bima**
Add a Korean translation file.

### CODE REVIEW

**Comment by croneter** [comment]
Thanks a lot! Please use [Transifex](https://www.transifex.com/croneter/pkc) next time!! It'll make things a LOT easier for both you and me. It says this in [CONTRIBUTING.MD](https://github.com/croneter/PlexKodiConnect/blob/master/CONTRIBUTING.md) as well. 

Example where I need to fix stuff - would not happen with Transifex:
```
msgctxt "#30030"
msgid "Port Number"
msgstr ""포트 번호
```

**Comment by croneter** [comment]
I can import your file into Transifex rather easily, will do that and merge into newest beta versions!

**Comment by croneter** [comment]
6 strings are still missing, please login to edit https://www.transifex.com/croneter/pkc/language/ko_KR/

**Comment by croneter** [comment]
Implemented in:
* Kodi Leia: #1423 
* Kodi Matrix: pending

Thanks again!

**Comment by so-o-bima** [comment]
I signed up for the website.
I requested to join the team.
If the request is accepted, we will proceed with the translation.
Thank you.

**Comment by croneter** [comment]
Just accepted you - thx! 😉

**Comment by so-o-bima** [comment]
The translation is complete.
Thank you for the best add-on development.
I pray that you are always healthy and only good things happen.

**Comment by croneter** [comment]
Thanks so much, indeed! ❤️  May you stay healthy and happy, too 😉

**Pull request closed without merging**
