### PR TITLE
Fix PKC not working properly if several Kodi video database versions are available, e.g. after an update of Kodi. Also fix sqlite3.OperationalError: table streamdetails has no column named strhdrtype (thanks @Son-Typ)

### LINKED ISSUE #1963: Some episodes now showing up on the tv show section?
I have 3 unwatched episodes of a show. When I go to the show those 3 episode don't show up. One of the episodes shows up in the on deck section. Normally in the on deck section I can click and hold on an episode and it'll bring up a list of options including an option to see all of the episodes of the tv show season. This show doesn't have that option though.

The show works in the official plex app and in composite, so it's not a problem with plex itself.

### LINKED ISSUE #1964: table streamdetails has no column named strhdrtype?
Sometimes when I'm watching a video this pops up

table streamdetails has no column named strhdrtype

It seems to also happen when plexkodiconnect tries to scan my library. Is there anyway to fix this? It's kind of distracting when I'm watching a video.

Also, would it be related to this problem I have:

https://github.com/croneter/PlexKodiConnect/issues/1963

### PR DESCRIPTION
**Pull request by croneter**
- Fixes #1964 
- Fixes #1963
- Thanks @Son-Typ !

### CODE REVIEW

**Comment by iirishguyi** [comment]
> * Fixes [table streamdetails has no column named strhdrtype? #1964](https://github.com/croneter/PlexKodiConnect/issues/1964)
> * Fixes [Some episodes now showing up on the tv show section?  #1963](https://github.com/croneter/PlexKodiConnect/issues/1963)
> * Thanks @Son-Typ !

Hey there! This is my first time being here!.....I'm ashamed to admit 😄 and I just recently discovered your Program or adding PlexKodiConnect....and it's INCREDIBLE to say the least, I'm blown away by the idea of incorporating your Plex with the customization of Kodi. It's great work. So with that being said.....I recently installed PKC and it runs fine as a program itself, but foe some unknown reason to me I'm having issues playing 4K, I have tried everything I can think of and I've gone over the instructions on how to set up the settings, so unless I did something wrong or my settings are all wrong I can't figure it out! 😄 it took a while but I'm now able to watch in HD or 1080 quality, but 4K just will not play. If at all possible if you wouldn't mind just going over the settings with me when you have some time.....I would be ever so grateful 😜 and FYI I am using a Shield PRO and my internet speed is above 200 so I'm pretty sure I got the basics covered lol. I appreciate all your help. If it's easier I can give you my email .....leeguy84@yahoo.com or my number if prefer to communicate that way. Or on here is fine, just let me know.  Thanks again!

**Comment by croneter** [comment]
@iirishguyi Welcome! 👋 Thanks for the praise. Unfortunately, PlexKodiConnect has literally NOTHING to do with you being or not being able to play 4k. PKC only tells Kodi which video file to play. Then everything else is up to Kodi (and Plex, i.e. the PMS needs to be able to stream 4K as well). So please start troubleshooting by looking at the Kodi side of things; the Kodi forums would be a good place to start. 

NOT PKC please, sorry to have to tell you...

Also - this Pull Request here on GitHub is a REALLY wrong place. A new GitHub issue would be more adequate 😉.

**Comment by iirishguyi** [comment]
Hey did you get my email? I responded back to the email I got notifying me of your response on here, so I wasn't sure if I could respond back through email? lol. I just really would like to be sure my settings are the way they should be that way I know it's Kodi and not something else......does that make sense? I never assumed it was PKC, I think what you created is amazing and it's agreat way to be able to use the customization of Kodi while watching movies on Plex

**Comment by croneter** [comment]
@iirishguyi  No I did not receive your email. Again: do not tinker with the PKC settings - they are not your problem. Good luck!

**Comment by iirishguyi** [comment]
I appreciate you responding back. That's fair enough, but I'm thinking perhaps I set something in the settings incorrectly, I'll be honest it's a little confusing and you have to change a few things, like the option to do a Direct Path, but in the instructions it pretty much recommends setting the path to ADDON. So I just need to be sure if they are correct. Would you mind just going over it with me or if you could send me a screenshot of how the settings are supposed to look? I would really appreciate it, and then I'll stop bugging you 😄 I really admire your work and creativity when you designed this program, I wish I could be that creative lol. Thanks again for all your help

**Pull request merged**
