### PR TITLE
Sync Plex Labels

### LINKED ISSUE #2042: [Feature Request] Plex Labels to Kodi Tags
Importing Plex Labels to Kodi Tags.

I'm a heavy user of Plex Labels and it would work well with kodi tags, I use just over 200 Netflix style genres as plex labels and if they were to be imported into Kodi as tags then my plex media would fit in nicely with my custom viewing experience created by 'Library Node Editor'.

My version of Netflix.....

MyFlix

😁

### PR DESCRIPTION
**Pull request by Spacetech**
PKC currently tags items with the Plex library name & collection name. This PR makes it sync the Plex Labels too.

Resolves #2042

### CODE REVIEW

**Comment by croneter** [comment]
Many thanks again. Food for thought: would it make sense to drop the existing labels PKC sets and only sync the Plex labels over to Kodi?

**Comment by Spacetech** [comment]
Yea that probably makes sense. Kodi Tags would then be 1:1 with Plex Labels. Or there could be new settings to allow including library name & plex collection names as Kodi tags too.

**Comment by croneter** [comment]
- Library names as tags: Years ago, some people used that to split Plex libraries in Kodi. Nowadays people should use https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins. Guess we could simply drop it. 
- Collections as tags: that's a workaround for Kodi not supporting a movie belonging to several Kodi sets. see https://github.com/croneter/PlexKodiConnect/discussions/1381. As far as I understand this is still not supported, https://kodi.wiki/view/Movie_sets

What do you think?

**Comment by thorindwarf** [comment]
I'm still using Tags in custom Kodi playlists to filter out video items from different libraries e.g. Kids Movies not showing in Movies.

**Pull request merged**
