### PR TITLE
Hungarian translation updated

### PR DESCRIPTION
**Pull request by savage93**
I've updated the Hungarian translation to reflect the recent changes.

### CODE REVIEW

**Comment by croneter** [comment]
Thanks very much.

We've been using Transifex for ages and it should be documented here on Github all over the place. It's much simpler for you and me to just use Transifex next time! https://www.transifex.com/croneter/pkc/dashboard/

I will thus have to manually download your strings and upload them to Transifex...

**Comment by croneter** [comment]
PR #651 will take care of this (Transiflex "work-flow")

**Comment by savage93** [comment]
@croneter I would gladly use Transifex, but their password reset emails never arrive in my Gmail mailbox, and thus I cannot login to that site. They require the users to set a fairly complex password at registration, which I have apparently forgotten. I am sorry for the hassle caused by this, but this problem with their password reset function has not been resolved in months...

**Comment by croneter** [comment]
No worries, takes me 2 minutes

**Pull request closed without merging**
