### PR TITLE
set artwork

### PR DESCRIPTION
**Pull request by im85288**

### CODE REVIEW

**Comment by croneter** [comment]
Resolves #44

**Comment by croneter** [comment]
Many thanks, by the way!! :-D

**Comment by im85288** [comment]
No problem at all..extra bling always helps!

We could go a step further and automatically create the sets as TMDB provides the "part of collection" tag...but that would take a little bit more logic to firstly assure you have at least two movies from that collection in your library. Definitely do-able though and would really be the icing on the cake :)

**Comment by croneter** [comment]
I agree that it would be a big benefit if PKC could help with the actual set creation as Plex is not very strong with that. Biggest challenge to that is deciding whether there exist several movies to a specific set. 

OR - and this would save us some headaches - does Kodi ignore sets with only one movie, so you would not have to first select the set, then select the one single movie in it?

**Comment by im85288** [comment]
Agreed - the Or part would be the most simple implementation but like you I am not sure how Kodi handles single set movies. Thinking about it though we could probably just do it and advertise it as a feature...worst case is that you have to do an extra click in Kodi which personally I would not mind and for anyone complaining we can always ask them to turn off the "group in sets" option in Kodi. 

Cool thing about doing it the easy way is that any new movie added would just go into the collection/set automatically.

**Comment by croneter** [comment]
Good news - Kodi ignores sets with only 1 movie in them! :-)

**Pull request merged**
